


alias rm~='rm -f *~ '
alias rm='rm -f '
alias find_by_name='find $(readlink -f `pwd`) -name '
alias findf_by_name='find $(readlink -f `pwd`) -type f -name '
#alias lshp='(find $(readlink -f `pwd`) -print0 -type f -name "*" | xargs -0 ls -th | head ) 2>/dev/null'
#alias lshp='( (find $(readlink -f `pwd`) -print0 -type f -name "*" | xargs -0 ls -th ) | head  ) 2>/dev/null'
alias lshp='perl $perl_p/lshp.PL '
alias ls_big_fn='perl $perl_p/ls_big_fn.PL '
alias lsi='docker images'
alias lsc='docker ps -a|grep 102'
alias c='clear '
alias objd='objdump '
alias mdb_run_elf='mdb -run -av2hs -cl '
alias mdb_dbg_elf='mdb -cl -av2hs '
alias perl_create_makefile=' perl $perl_p/auto_create_makefile_OK.PL > Makefile && echo "create Makefile and [make all] " && make all '
alias perl_show_files_content='perl $perl_p/show_file_content.PL '
alias perl_mqx_config='yes|cp -u $perl_p/mqx_*config*.PL ./mqx_config && perl mqx_config '
alias cp_to_bak='sh $perl_p/cp_to_bak.sh '
alias ia_2013='/slowfs/us01dwt2p448/flexera/InstallAnywhere_2013/InstallAnywhere'
alias ia_2014='/slowfs/us01dwt2p448/flexera/InstallAnywhere_2014-SP1/InstallAnywhere'
alias ia_build='/slowfs/us01dwt2p448/flexera/InstallAnywhere_2014-SP1/build'
alias RE='cat $perl_p/README '
alias s_bashrc='source ~/.bashrc'
alias s_b='source ~/.bashrc'
alias cygpath='$perl_p/cygpath_aw.sh '
alias archi_env_set='sh $perl_p/architect_set_env.sh '
alias perl_diff_foler='perl $perl_p/diff_ia_folder_R1_R0.PL '
alias lsh=' perl $perl_p/lsh.PL ' 
alias readlink_file=' perl $perl_p/readlink_file.PL ' 
alias see_path='sh $perl_p/see_path.sh '
alias scp_it='perl $perl_p/scp_it.PL '
alias scp_it_outside='perl $perl_p/scp_it_outside.PL '
alias full_path='perl $perl_p/full_path.PL '
alias full='perl $perl_p/full_path.PL '
alias ff='perl $perl_p/ff.PL ' 
alias agl='cd $agl' 
alias tol='perl $perl_p/tol.PL ' 
alias jdvm='ssh root@localhost -p 10249'

#alias fr='perl $perl_p/fr.PL'
#alias tor='perl $perl_p/tor.PL'
#alias cct='python3 $perl_p/cct.py'

alias peval='perl $perl_p/peval.PL ' 
alias sc='perl $perl_p/sc.PL ' 
alias latest_info='(basename `full_ $latest_mwdt` && basename `dirname \`full_ $latest_mide\`` ) | tee $tmp/perl_p/latest_info.log'
alias s_l='source ~/txt.txt && export PATH=/SCRATCH/ARC/ARC_/MetaWare/ide:$PATH'
alias setenv_latest_mwdt_mide='latest_info && perl $perl_p/setenv_latest_mwdt_mide.PL && s_l '
alias setenv_daily_mide='perl $perl_p/setenv_daily_mide.PL '
alias cc_test='perl $perl_p/cc_test_linux.PL '
alias ecd='perl $perl_p/ecd.PL '
alias qftest='${qftest_root}/qftest -license ~linqi/license/qft_lic.dat '
alias qft_code_gen=' cd $perl_p && perl $perl_p/qft_code_gen.PL '
alias gen_qft_code=' perl $perl_p/gen_qft_code.PL '
alias g='gedit '
#alias h='history '
alias chmod_r='chmod -R 0775 `pwd` '
alias QSUB='qsub -P bnormal -cwd -V -l arch=glinux,os_bit=64,cputype=emt64,os_distribution=redhat'
#get an xterm
alias xlight='qsh -P ilight -display $DISPLAY_USE -l arch=glinux,os_bit=64 -- -bg Azure1'
alias xheavy='qsh -P iheavy -l os_version=WS6.0'
alias xheavy32='qsh -P iheavy -l os_version=WS6.0,os_bit=32'
#bsub an interactive job
alias qheavy='qrsh -P iheavy -l os_version=WS4.0 -now no -b y'
alias qft_env_='cat $qft_mide/script/*.sh |grep env_ '
alias cbin='perl $perl_p/cbin.PL ' 
alias mc='cd $rmo && sh startup_mongo.sh ' 
alias map_='perl $perl_p/map_.PL ' 
alias psf='ps -u $USER -f ' 
alias nll='nl -w 4 -b a -n rz ' 
alias t='cd $t'
alias tt='cd $tt'
alias et='cd $et'
# alias gs='cd $gs'
alias gss='cd $gss'
alias gss_='cd $gss_'
alias db='cd $db'

alias dg='newgrp - docker'
alias m_a2='perl $perl_p/m_a2.PL '

### new added ###
alias git_push='perl $perl_p/git_push.PL ';
alias git_reset='perl $perl_p/git_reset.PL ';
alias git_push_no_pw='perl $perl_p/git_push_no_pw.PL ';
alias gmain='gss_ && cp_to_bak main.cpp && rm main.cpp && git checkout --theirs main.cpp && git pull'
alias mail_bgi='perl $perl_p/mail_bgi.PL '
alias mount_sf_et='perl $perl_p/mount_sf_et.PL'
#alias bwa='cd $bwa'
alias L='perl $perl_p/L.PL'
alias psh='ps au --sort=lstart'
alias seq_2_num='perl $perl_p/seq_2_num.PL'
alias tmi='~/tell_my_ip/tell_my_ip '
alias ymail='python3 $perl_p/jd_yagmail.py'
alias fsrc='perl $perl_p/filter_src_fn.PL' 
alias vb='vim $HOME/.bashrc'
export bk=$t/bak_script
alias bk='cd $bk'
alias tarc='tar czf '
alias tart='tar tzf '
alias tarx='tar xvzf '
alias del='rm '
alias p='pushd '
alias pd='popd '
alias gvim='vim '
alias gl='git log --all -55 --name-status'
alias gs='perl $perl_p/gs.PL'
alias git_save='perl $perl_p/git_opts.PL git_save'
alias git_reset='perl $perl_p/git_opts.PL git_reset'
alias git_merge='perl $perl_p/git_opts.PL git_merge'


#alias gdb='cgdb'

### jd add gt
